name: Terraform Destroy
on:
 workflow_dispatch:  
jobs:
  terraform:
    name: "Apply Terraform Code Changes"
    runs-on: ubuntu-latest
    env:
    # Credenciales AWS
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1'
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v1

      - name: Instala Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "0.12.15"
      - name: Verificar instalación de Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/0.12.15/terraform_0.12.15_linux_amd64.zip
          unzip terraform_"$terraform_version"_linux_amd64.zip
          sudo mv terraform /usr/local/bin
          
      - name: Terraform Init
        run: terraform init -input=false # Inicializa y actualiza proveedores si es necesario

      - name: Terraform destroy
        run: terraform destroy -auto-approve
