name: Terraform Destroy
on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Apply Terraform Code Changes"
    runs-on: ubuntu-latest
    env:
      # Credenciales AWS
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1'

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "0.12.15"

      - name: Verificar versión de Terraform
        run: terraform version

      - name: Terraform Init
        working-directory: infra
        run: terraform init -input=false

      - name: Terraform Destroy
        working-directory: infra
        run: terraform destroy -auto-approve
